# Instructions shown when choosing the instructions option in the menu.
def show_instructions():
    print("You can view the logos and icons used in this game in the README file in the folder containing the game")
    print("This game is played by following the prompts.")
    print("In the menu, please type in the relevant number and press the enter key.")
    print("If you've chosen to view the instructions you can then press enter again to return to the menu.")
    print("If you've chosen to play the game, the game will give you a hint then prompt you for a colour name.")
    print("Please type in the colour name in lower cased letters, then press enter.")
    print("If you type in the incorrect colour or any other word that is not the colour, it will count as an incorrect guess and you'll be given a new hint for the same colour.")
    print("Remember you only have five guesses!")
    print("If you don't guess correctly within those five guesses, you'll be asked if you want to play again.")
    print("Please type in 'yes' or 'no' and press enter.")
    print("If you guessed correctly, you'll be given a score based on how many guesses it took and will be asked if you'd like to play again.")
    print("If you guess correctly in multiple rounds, you'll be shown your total score for all the rounds you've played if you haven't exited the game.")
    print("When you're done playing, you can choose 'no' to playing again, or exit the terminal at any point.")
    print("Thanks for playing the game!")
